const dataset=window.CRudeOilDataset||{headers:[],records:[]};
const records=dataset.records||[];
const headerMap=Object.fromEntries((dataset.headers||[]).map((item)=>[item.key,item.label]));
const state={query:"",crudeClass:"",origin:"",selectedId:records[0]?.id||null};
const $=(selector)=>document.querySelector(selector);
const fields={datasetMeta:$("#datasetMeta"),totalCount:$("#totalCount"),searchInput:$("#searchInput"),clearButton:$("#clearButton"),resetButton:$("#resetButton"),classFilter:$("#classFilter"),originFilter:$("#originFilter"),resultBody:$("#resultBody"),resultCount:$("#resultCount"),activeMatch:$("#activeMatch"),detailPanel:$("#detailPanel")};
const propertyKeys=["origin","evaluationYear","apiGravity","sulfur","acidValue","pourPoint","flashPoint","viscosity50","carbonResidue","nickel","vanadium","crudeClass"];
const keyMetrics=["apiGravity","sulfur","acidValue","viscosity50"];
function normalizeText(value){return String(value??"").normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]+/gu,"");}
function displayValue(value){return value===null||value===undefined||value===""?"—":String(value);}
function isSubsequence(needle,haystack){let index=0;for(const char of haystack){if(char===needle[index]){index+=1;if(index===needle.length)return true;}}return false;}
function bigrams(text){if(text.length<2)return[text];const grams=[];for(let i=0;i<text.length-1;i+=1)grams.push(text.slice(i,i+2));return grams;}
function diceCoefficient(left,right){if(!left||!right)return 0;if(left===right)return 1;const a=bigrams(left);const b=bigrams(right);const counts=new Map();for(const gram of a)counts.set(gram,(counts.get(gram)||0)+1);let overlap=0;for(const gram of b){const count=counts.get(gram)||0;if(count>0){counts.set(gram,count-1);overlap+=1;}}return 2*overlap/(a.length+b.length);}
function levenshteinRatio(left,right){if(!left||!right||left.length>42||right.length>42)return 0;const previous=Array.from({length:right.length+1},(_,i)=>i);const current=new Array(right.length+1);for(let i=1;i<=left.length;i+=1){current[0]=i;for(let j=1;j<=right.length;j+=1){const cost=left[i-1]===right[j-1]?0:1;current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+cost);}previous.splice(0,previous.length,...current);}return 1-previous[right.length]/Math.max(left.length,right.length);}
function fuzzyScore(query,target){const q=normalizeText(query);const t=normalizeText(target);if(!q)return 1;if(!t)return 0;if(q===t)return 1;if(t.includes(q))return Math.max(.72,q.length/Math.max(t.length,1));if(isSubsequence(q,t))return .64;return Math.max(diceCoefficient(q,t),levenshteinRatio(q,t));}
function scoreRecord(record){if(!state.query)return 1;const nameScore=Math.max(fuzzyScore(state.query,record.cnName),fuzzyScore(state.query,record.enName));const contextScore=Math.max(fuzzyScore(state.query,record.origin)*.62,fuzzyScore(state.query,record.crudeClass)*.58);return Math.max(nameScore,contextScore);}
function minimumScore(){const query=normalizeText(state.query);if(!query)return 0;return /^[a-z0-9]+$/i.test(query)&&query.length>=3?.63:.42;}
function sortedUnique(key){return[...new Set(records.map((r)=>r[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),"zh-Hans-CN"));}
function fillSelect(select,items,emptyLabel){select.replaceChildren();const empty=document.createElement("option");empty.value="";empty.textContent=emptyLabel;select.append(empty);for(const item of items){const option=document.createElement("option");option.value=item;option.textContent=item;select.append(option);}}
function getFilteredRecords(){const scored=records.map((record)=>({record,score:scoreRecord(record)})).filter(({record,score})=>{if(state.crudeClass&&record.crudeClass!==state.crudeClass)return false;if(state.origin&&record.origin!==state.origin)return false;return !state.query||score>=minimumScore();});scored.sort((a,b)=>b.score-a.score||String(a.record.cnName).localeCompare(String(b.record.cnName),"zh-Hans-CN"));return scored;}
function renderResults(scored){fields.resultBody.replaceChildren();if(!scored.length){const row=document.createElement("tr");const cell=document.createElement("td");cell.className="no-results";cell.colSpan=5;cell.textContent="未找到匹配油种";row.append(cell);fields.resultBody.append(row);return;}const fragment=document.createDocumentFragment();for(const {record} of scored){const row=document.createElement("tr");row.tabIndex=0;row.dataset.id=record.id;row.classList.toggle("is-selected",record.id===state.selectedId);row.innerHTML=`<td><div class="oil-name"><strong>${displayValue(record.cnName)}</strong><span>${displayValue(record.enName)}</span></div></td><td>${displayValue(record.origin)}</td><td>${displayValue(record.apiGravity)}</td><td>${displayValue(record.sulfur)}</td><td><span class="badge">${displayValue(record.crudeClass)}</span></td>`;fragment.append(row);}fields.resultBody.append(fragment);}
function renderDetail(record){fields.detailPanel.replaceChildren();if(!record){const empty=document.createElement("div");empty.className="detail-empty";empty.textContent="选择一个油种查看性质";fields.detailPanel.append(empty);return;}const title=document.createElement("div");title.className="detail-title";title.innerHTML=`<div><h2>${displayValue(record.cnName)}</h2><p>${displayValue(record.enName)} · ${displayValue(record.origin)}</p></div><span class="detail-index">#${displayValue(record.index)}</span>`;const metrics=document.createElement("div");metrics.className="key-metrics";for(const key of keyMetrics){const metric=document.createElement("div");metric.className="metric";metric.innerHTML=`<span>${headerMap[key]||key}</span><strong>${displayValue(record[key])}</strong>`;metrics.append(metric);}const grid=document.createElement("div");grid.className="property-grid";for(const key of propertyKeys){const item=document.createElement("div");item.className="property";item.innerHTML=`<span>${headerMap[key]||key}</span><strong>${displayValue(record[key])}</strong>`;grid.append(item);}fields.detailPanel.append(title,metrics,grid);}
function syncSelected(scored){const ids=new Set(scored.map(({record})=>record.id));if(!ids.has(state.selectedId))state.selectedId=scored[0]?.record.id||null;}
function render(){const scored=getFilteredRecords();syncSelected(scored);fields.resultCount.textContent=`${scored.length} 条结果`;fields.activeMatch.textContent=state.query?"模糊匹配":"按相关度排序";renderResults(scored);renderDetail(records.find((record)=>record.id===state.selectedId));}
function init(){fields.datasetMeta.textContent=`${dataset.title||"进口原油基本性质"} · ${dataset.sourceFile||""}`;fields.totalCount.textContent=records.length;fillSelect(fields.classFilter,sortedUnique("crudeClass"),"全部类别");fillSelect(fields.originFilter,sortedUnique("origin"),"全部产地");fields.searchInput.addEventListener("input",(event)=>{state.query=event.target.value.trim();render();});fields.clearButton.addEventListener("click",()=>{fields.searchInput.value="";state.query="";fields.searchInput.focus();render();});fields.resetButton.addEventListener("click",()=>{state.query="";state.crudeClass="";state.origin="";fields.searchInput.value="";fields.classFilter.value="";fields.originFilter.value="";render();});fields.classFilter.addEventListener("change",(event)=>{state.crudeClass=event.target.value;render();});fields.originFilter.addEventListener("change",(event)=>{state.origin=event.target.value;render();});fields.resultBody.addEventListener("click",(event)=>{const row=event.target.closest("tr[data-id]");if(!row)return;state.selectedId=row.dataset.id;render();});fields.resultBody.addEventListener("keydown",(event)=>{if(event.key!=="Enter"&&event.key!==" ")return;const row=event.target.closest("tr[data-id]");if(!row)return;event.preventDefault();state.selectedId=row.dataset.id;render();});render();fields.searchInput.focus();}
init();
